version: '3.7'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    networks:
      - monitoring
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki:/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - 9080:9080
      - 9095:9095
      - 1514:1514/udp
    networks:
      - monitoring
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Testing@123
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - loki

volumes:
  loki:
  grafana:
    driver: local

networks:
  monitoring:
    driver: bridge