services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 2100:3100
    networks:
      - monitoring
    restart: always
    volumes:
      - loki:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 2000:3000
    networks:
      - monitoring
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Testing@123
    volumes:
      - grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

volumes:
  loki:
    name: 'loki'
    driver: local
  grafana:
    name: 'grafana'
    driver: local

networks:
  monitoring:
    name: "monitoring"
    driver: bridge
