server:
  http_listen_port: 3100
  grpc_listen_port: 9095

distributor:
  ring:
    kvstore:
      store: inmemory  # Use in-memory store instead of Consul

ingester:
  chunk_idle_period: 5m
  chunk_block_size: 104857600  # 100MB in bytes
  max_chunk_age: 1h
  flush_op_timeout: 1m
  chunk_retain_period: 1h
  wal:
    dir: /loki/wal  # Custom WAL directory

storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

table_manager:
  retention_deletes_enabled: true
  retention_period: 30d
