auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  chunk_idle_period: 5m
  chunk_block_size: 104857600  # 100MB
  max_chunk_age: 1h
  flush_op_timeout: 1m
  chunk_retain_period: 1h
  wal:
    dir: /loki/wal

distributor:
  ring:
    kvstore:
      store: inmemory

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    # filesystem:
    #   chunks_directory: /tmp/loki/chunks
    #   rules_directory: /tmp/loki/rules
      
    s3: 
      bucketnames: "eternals"
      endpoint: "http://140.238.255.244:8100"
      insecure: true
      region: "us-east-1"
      access_key_id: "ZN0kFCLlLlqxx3s1Ur06"
      secret_access_key: "UYPNDl4Rzc3dnf3U2Ypa9XwgB7nOvmc69NrYOnST"
      sse_encryption: true  # Enable server-side encryption
      s3forcepathstyle: true  # Use path-style URLs (required for MinIO)

  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      # object_store: filesystem
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h