auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  chunk_idle_period: 5m
  chunk_block_size: 104857600  # 100MB in bytes
  max_chunk_age: 1h
  flush_op_timeout: 1m
  chunk_retain_period: 1h
  wal:
    dir: /loki/w

distributor:
  ring:
    kvstore:
      store: inmemory

storage_config:
  boltdb:
    directory: /loki/data

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
