server:
  http_listen_port: 9080        # Promtail HTTP listening port (for status and metrics)
  grpc_listen_port: 9095        # Promtail gRPC listening port

positions:
  filename: /tmp/positions.yaml  # Where Promtail keeps track of the last scraped positions in log files

clients:
  - url: http://loki:3100/loki/api/v1/push  # Loki API endpoint for sending logs

scrape_configs:
  # Scrape logs from /var/log directory
  - job_name: 'system'
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log  # Path to the log files

  # Scrape logs via UDP (syslog format)
  - job_name: 'syslog'
    static_configs:
      - targets: ['localhost']
    syslog:
      listen_address: 0.0.0.0:1514  # Promtail Syslog UDP receiver
      idle_timeout: 60s
      label_structured_data: true
      labels:
        job: syslog